### ISSUE TITLE
[bug]: omits first Row in TableBody of the Mapper 

### ISSUE THREAD

**Issue by RocketDav1d** [sadmann7/csv-importer#3]
### Describe the bug

First of all, thanks for building such a great component, I really appreciate it. 

In the Mapping of the CSVImporter I've noticed that it omits the first row of the uploaded csv file. 
The reason for that is in the onParse function. With this onParse function it successfully keeps the first data row 

https://gist.github.com/RocketDav1d/524409b6021ed1e3a89b10caf7441bf0

### How to reproduce

simply clone the repo and run the app, then upload a csv

### Link to reproduction

/

**Comment by sadmann7** [comment]
thanks.

if you wanna make a pr for it that would be great.

**Comment by dylancetin** [comment]
@sadmann7 i think we can close this now
