### ISSUE TITLE
no need to upload the file to uploadthing

### ISSUE THREAD

**Issue by jpainam** [sadmann7/csv-importer#4]
### Describe the bug

N/A

### How to reproduce

N/A

### Link to reproduction

N/A

### Additional information

I don't think it's necessarily to upload the file to uploadthing. because the parsing with `papaparse` is done with the locally loaded file.
The file is usually not used afterwards.

https://github.com/sadmann7/csv-importer/blob/b4970182306589b6baa77ff424ff15f078dd1146/src/components/csv-importer.tsx#L135

**Comment by sadmann7** [comment]
its for tracking analytics and stuffs on what file is being imported

you can just use the `onValueChange` props to handle the parsing without uploading
